[package]
name = "node-forge-render-server"
version = "0.1.0"
edition = "2024"

[dependencies]
rust-wgpu-fiber = {version = "*", path = "../rust-wgpu-fiber"}
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
crossbeam-channel = "0.5"
tungstenite = "0.21"